apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mycelium-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: mycelium.harismawan.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /mcp
            pathType: Prefix
            backend:
              service:
                name: mycelium-mcp-service
                port:
                  number: 3001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mycelium-web-service
                port:
                  number: 80
