apiVersion: v1
kind: ConfigMap
metadata:
  name: mycelium-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  MCP_TRANSPORT: "http"
  MCP_PORT: "3001"
  CORS_ORIGIN: "https://mycelium.harismawan.com"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://192.168.100.31:8200"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRIC_EXPORT_INTERVAL: "60000"
  OTEL_LOG_LEVEL: "error"
  OTEL_DEPLOYMENT_ENVIRONMENT: "production"
