apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycelium-api
spec:
  selector:
    matchLabels:
      app: mycelium-api
  template:
    metadata:
      labels:
        app: mycelium-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: mycelium-api
          image: ghcr.io/harismawan/mycelium-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: 1
            requests:
              memory: "128Mi"
              cpu: 0.1
          envFrom:
            - configMapRef:
                name: mycelium-config
            - secretRef:
                name: mycelium-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
